# Prática

## Array

### Importando biblioteca

In [ ]:
# Import biblioteca
import numpy as np

### Informações básicas de um array

In [ ]:
# Gerando um array com duas listas
arr = np.array([[1, 2, 3], [4, 5, 6]], int)
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# shape
arr.shape

(2, 3)

In [ ]:
# ndim
arr.ndim

2

In [ ]:
# dtype
arr.dtype

dtype('int64')

In [ ]:
# Tentando criar um array com listas de tamanho diferente
# arr_2 = np.array([[1, 2, 3, 4], [5, 6]])

In [ ]:
# Criando array com np.zeros
arr = np.zeros((2, 2), int)
arr

array([[0, 0],
       [0, 0]])

In [ ]:
# Criando array com np.identity
arr = np.identity(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Computação Vetorizada

### Aritmética

In [ ]:
arr_1 = np.arange(5)

arr_2 = np.arange(5, 10)

print(arr_1)

print(arr_2)

[0 1 2 3 4]
[5 6 7 8 9]


In [ ]:
# Operação entre arrays
arr_1 + arr_2

array([ 5,  7,  9, 11, 13])

In [ ]:
# Operação com escalar
arr_1 * 2

array([0, 2, 4, 6, 8])

### Comparações

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr2 = np.array([1, 2, 5, 4, 3, 6])

print(arr1)
print(arr2)

[1 2 3 4 5 6]
[1 2 5 4 3 6]


In [ ]:
# Comparação entre arrays


arr1 >= arr2

array([ True,  True, False,  True,  True,  True])

In [ ]:
# Comparação com escalar
arr1 > 2

array([False, False,  True,  True,  True,  True])

In [ ]:
# Combinação de comparações

(arr1 > 2) & (arr1 == arr2)

array([False, False, False,  True, False,  True])

### Indexação e fatiamento

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Indexação por índice com 1 dimensão
arr[1]

array([4, 5, 6])

In [ ]:
# Indexação por índice com mais dimensões
arr[1, 2]

6

In [ ]:
# Indexação por fatiamento

arr[1:2]

array([[4, 5, 6]])

In [ ]:
# Fatiamento Vazio
arr[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Visualizando linhas
arr[1, :]

array([4, 5, 6])

In [ ]:
# Visualizando colunas
arr[:, 1]

array([2, 5, 8])

In [ ]:
# Indexação por vetor: array unidimensional
arr_unidimensional = arr[arr > 3]

In [ ]:
# Reshape
new_arr = arr_unidimensional.reshape((2, 3))
new_arr

array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Referencia: Alterando copia da fatia
arr_cp = new_arr.copy()
arr_cp[:, 1] = -1
new_arr


array([[4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Referencia: Alterando a fatia
new_arr[:, 1] = -1
new_arr

array([[ 4, -1,  6],
       [ 7, -1,  9]])

In [ ]:
# Olhando array unidimensional
arr_unidimensional

array([ 4, -1,  6,  7, -1,  9])

## Estatística para numpy

### Estatísticas descritivas

In [ ]:

arr = np.linspace(0, 20, 21)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20.])

In [ ]:
# Média
arr.mean()

10.0

In [ ]:
# Máximo
arr.max()

20.0

In [ ]:
# Mínimo
arr.min()

0.0

In [ ]:
# Índice máx
arr.argmax()

20

In [ ]:
# Índice min
arr.argmin()

0

In [ ]:
# Desvio padrao
arr.std()

6.0553007081949835

In [ ]:
# Soma
arr.sum()

210.0

In [ ]:
# Soma cumulativa
arr.cumsum()

array([  0.,   1.,   3.,   6.,  10.,  15.,  21.,  28.,  36.,  45.,  55.,
        66.,  78.,  91., 105., 120., 136., 153., 171., 190., 210.])

### Mini - exercício

Selecione os valores que se distanciam da média até um desvio padrão

## Funções universais

In [ ]:
# Mediana
np.median(arr)

10.0

In [ ]:
# Percentil
np.percentile(arr, 33)

6.6000000000000005

In [ ]:
# seno
arr = np.array([0, np.pi / 2])

In [ ]:
# Adição de arrays
arr1 = np.array([9, 9, 9, 9, 9])
arr2 = np.array([6, 7, 8, 9, 10])

np.add(arr1, arr2)

array([15, 16, 17, 18, 19])

In [ ]:
#maximum
np.maximum(arr1, arr2)

array([ 9,  9,  9,  9, 10])

In [ ]:
# modf
arr = np.random.uniform(0.0, 10.0, 6)
np.modf(arr)

(array([0.28265933, 0.89006163, 0.53838076, 0.36314423, 0.2325095 ,
        0.03925409]),
 array([1., 1., 9., 3., 6., 5.]))

## Algebra Linear

In [ ]:
mtx = np.eye(3) + [1, 1.5, 3]
mtx

array([[2. , 1.5, 3. ],
       [1. , 2.5, 3. ],
       [1. , 1.5, 4. ]])

In [ ]:
vet = np.array([1, 2, 3])
vet

array([1, 2, 3])

In [ ]:
# Multiplicação de matrizes: .dot e @
mtx.dot(vet)

array([14., 15., 16.])

In [ ]:
mtx @ vet

array([14., 15., 16.])

In [ ]:
# Determinante
np.linalg.det(mtx)

6.500000000000001

In [ ]:
# Transposição

mtx.T

array([[2. , 1. , 1. ],
       [1.5, 2.5, 1.5],
       [3. , 3. , 4. ]])

In [ ]:
# Matriz inversa
np.linalg.inv(mtx)

array([[ 0.84615385, -0.23076923, -0.46153846],
       [-0.15384615,  0.76923077, -0.46153846],
       [-0.15384615, -0.23076923,  0.53846154]])

# Exercícios


## Exercício 1

Faça uma função que receba um array como entrada, remova o primeiro e o último elementos do array e retorne um novo array contendo os elementos restantes.

In [ ]:
# Código

original = np.array([2, 5, 7, 9, 1, 4, 6])

# Saída: [5 7 9 1 4]

### Resolução

In [ ]:
import numpy as np

def eliminaExtremos(original):
  return original[1:-1]

# Exemplo
original = np.array([2, 5, 7, 9, 1, 4, 6])
print(eliminaExtremos(original))

[5 7 9 1 4]


## Exercício 2

Crie um array com elementos de 0 a 100 e calcule a soma de todos os valores pares.

In [ ]:
# Código

# Saída: 2550

### Resolução

In [ ]:
import numpy as np

numeros = np.arange(101)
somaPares = np.sum(numeros[numeros % 2 == 0])

print(somaPares)

2550


## Exercício 3

Gere um array A contendo todos os números ímpares entre 0 e 100. A partir de A, crie outro array que contenha a soma cumulativa dos elementos de A que são divisíveis por 3 e 5 simultaneamente.

In [ ]:
# Código

# Saída: [15 60 135]

### Resolução

In [ ]:
import numpy as np

impares = np.arange(1, 100, 2)

multiplos3e5 = impares[(impares % 3 == 0) & (impares % 5 == 0)]
somaCumulativa = np.cumsum(multiplos3e5)

print(somaCumulativa)

[ 15  60 135]


## Exercício 4

Faça uma função que dados dois vetores (valores e pesos), calcule a média ponderada de valores com seus respectivos pesos.

Observação: não é permitido utilizar a função np.average do NumPy

In [ ]:
# Código

valores = np.array([1, 2, 5])
pesos = np.array([3, 2, 1])

# Saída: 2.0

### Resolução

In [ ]:
import numpy as np

def calculaMediaPonderada(valores, pesos):
  multiplicadoPesos = valores * pesos
  somaPesos = np.sum(pesos)
  mediaPonderada = np.sum(multiplicadoPesos) / somaPesos
  return mediaPonderada

valores = np.array([1, 2, 5])
pesos = np.array([3, 2, 1])

print(calculaMediaPonderada(valores, pesos))

2.0


## Exercício 5

Considere um array bidimensional no qual cada vetor de uma dimensão possui 3 pontuações que um jogador recebeu em 3 provas distintas. Faça uma função que dado esse array, retorne a prova com maior soma de pontuações.

In [ ]:
# Código

pontuacoes = [[6.5, 7.8, 5.4], [9.5, 8.8, 9.1], [4.5, 7.3, 5.9]]

# Saída: 23.9

### Resolução

In [ ]:
import numpy as np

def maiorPontuacao(pontuacoes):
  pontuacoesNP = np.array(pontuacoes)
  somaPorProva = np.sum(pontuacoesNP, axis = 0)
  maiorSoma = np.max(somaPorProva)
  return maiorSoma

# Exemplo para 3 jogadores
pontuacoes = [[6.5, 7.8, 5.4], [9.5, 8.8, 9.1], [4.5, 7.3, 5.9]]

print("%.1f" % ((maiorPontuacao(pontuacoes))))

23.9


## Exercício 6

Você é um professor e está organizando as notas de seus alunos. Para tanto, você precisa realizar algumas tarefas, como:

  - Determinar a média das notas
  - Determinar a maior e a menor notas e os alunos que as tiraram
  - Determinar as notas dos alunos aprovados e reprovados

Considere que são aprovados os alunos com notas maiores ou iguais a 5.0.

In [ ]:
# Código

notas = np.array([2.5, 7.8, 6.7, 9.4, 3.8, 5.1, 4.4, 8.2])

### Resolução

In [ ]:
import numpy as np

def analisaNotas(notas):
  media = np.mean(notas)
  maiorNota = np.max(notas)
  menorNota = np.min(notas)
  maiorNotaAluno = np.argmax(notas)
  menorNotaAluno = np.argmin(notas)

  notaCorte = 5.0

  alunosAprovados = notas[notas >= notaCorte]
  alunosReprovados = notas[notas < notaCorte]

  print(f"Média das notas: %.1f" % (media))
  print(f"Maior nota: {maiorNota} - Aluno: {maiorNotaAluno}")
  print(f"Menor nota: {menorNota} - Aluno: {menorNotaAluno}")
  print(f"Notas dos Alunos aprovados: {alunosAprovados}")
  print(f"Notas dos Alunos reprovados: {alunosReprovados}")

notas = np.array([2.5, 7.8, 6.7, 9.4, 3.8, 5.1, 4.4, 8.2])

analisaNotas(notas)

Média das notas: 6.0
Maior nota: 9.4 - Aluno: 3
Menor nota: 2.5 - Aluno: 0
Notas dos Alunos aprovados: [7.8 6.7 9.4 5.1 8.2]
Notas dos Alunos reprovados: [2.5 3.8 4.4]


## Exercício 7

Um quadrado mágico é todo quadrado de lado $n$ em que os inteiros de 1 a $n^2$ aparecem sem repetição e em que as somas dos elementos das linhas, colunas e diagonais são iguais.

Faça uma função que recebe uma matriz quadrada e que verifique se ela é um quadrado mágico ou não.

Exemplo: O quadrado
$
\begin{bmatrix}
2 & 9 & 4 \\
7 & 5 & 3 \\
6 & 1 & 8
\end{bmatrix}
$
é um quadrado mágico. Observe que as linhas, colunas e diagonais possuem soma igual a 15.

In [ ]:
# Código

quadradoMagico = np.array([[2, 7, 6], [9, 5, 1], [4, 3, 8]])
quadradoNaoMagico = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Saída: "É um quadrado mágico"
# Saída: "Não é um quadrado mágico"

### Resolução

In [ ]:
import numpy as np

# Retorna True se quadrado mágico
# Retorna False caso contrário
def verificaQuadradoMagico(quadrado):
  n = quadrado.shape[0]

  # .flatten() cria uma cópia em 1 dimensão de "quadrado"
  quadradoUnidimensional = quadrado.flatten()

  # Ordena quadradoUnidimensional em ordem crescente
  # Verifica se quadradoUnidimensional e o vetor de 1 a n^2 são iguais
  if not np.array_equal(np.sort(quadradoUnidimensional), np.arange(1, n**2 + 1)):
    return False

  # Pega a soma da primeira linha como base
  soma = np.sum(quadrado[0, :])

  # Verifica se todas as colunas (axis = 1) possuem a mesma soma
  if not np.all(np.sum(quadrado, axis = 1) == soma):
    return False

  # Verifica se todas as linhas (axis = 0) possuem a mesma soma
  if not np.all(np.sum(quadrado, axis = 0) == soma):
    return False

  # Veriica se a diagonal principal possui a mesma soma
  if np.sum(np.diag(quadrado)) != soma:
    return False

  # Veriica se a diagonal secundária possui a mesma soma
  if np.sum(np.diag(np.fliplr(quadrado))) != soma:
    return False

  return True

quadradoMagico = np.array([[2, 7, 6], [9, 5, 1], [4, 3, 8]])
quadradoNaoMagico = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

if verificaQuadradoMagico(quadradoMagico):
  print("É um quadrado mágico.")
else:
  print("Não é um quadrado mágico.")

if verificaQuadradoMagico(quadradoNaoMagico):
  print("É um quadrado mágico.")
else:
  print("Não é um quadrado mágico.")

É um quadrado mágico.
Não é um quadrado mágico.
